### ISSUE TITLE
tex-buf.el has been merged into tex.el

### ISSUE THREAD

**Issue by tarsius** [dandavison/xenops#48]
I've noticed this because I maintain the [Emacsmirror](https://emacsmirror.org) and the tools, that I use to do so, inform me when a dependency of a mirrored package isn't satisfied (anymore).

In `auctex` [`tex-buf.el` was merged into `tex.el`](https://github.com/emacsmirror/auctex/commit/4b1c7015ae77b88832af35510232e1a1b716da3a) but your package still `require`s `tex-buf`. You can probably fix this by depending on `tex` instead, or if you already do that by dropping the additional `(require 'tex-buf)`.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by dandavison** [comment]
Hi @tarsius, thanks. I sort-of addressed this in https://github.com/dandavison/xenops/pull/40 which made it no longer an error if `tex-buf` was not available. I was thinking that leaving it in that state -- rather than deleting the `require` entirely -- was good for backwards compatibility, i.e. for people who still have the old version of auctex installed. It [looks like](https://github.com/dandavison/xenops/blob/master/lisp/xenops.el#L6) my declared dependency is on `auctex "12.2.0"` which I think still has `tex-buf.el`. What do you think -- is that backwards-compatibility argument reasonable?

**Comment by tarsius** [comment]
Thanks!
